mariadb:
  host: "localhost"
  user: "root"
  password: "root"
  database: "ecMeteor"
  port: 3306

gui:
  title: "Магия Метеор"
  size: 9
  buttons:
    meteor:
      slot: 4
      name: "Метеор"
      material: LIME_SHULKER_BOX
      lore:
        - ""
        - "&a[ЛКМ] &f- Чтобы активировать магию"
        - ""
    info-meteor:
      slot: 0
      name: "Информация о Метеоре"
      material: PAPER
      lore:
        - ""
        - "&fСама способность при клике ЛКМ создаёт “метеор”,"
        - "&fкоторый летит в направлении взгляда."
        - "&fСам метеор выглядит как кастомным снарядом гаста."
        - ""
        - "&fМетеор летит, пока не встретит препятствие (сущность или блок). "
        - "&fУдарившись в препятствие, он взрывается множеством частиц,"
        - "&fвременно уничтожая блоки вокруг."
        - ""
        - "Помимо уничтожения блоков, взрыв также издаёт звук, "
        - "наносит урон и подбрасывает в воздух всех сущностей поблизости."
        - ""

